version: '3'

services:
  app:
    image: kevinduy/vuejs
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8080:8080"
    tty: true
